volumes:
  logstashdata01:
    driver: local

networks:
  default:
    name: elastic
    external: false

services:
  logstash01:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    labels:
      co.elastic.logs/module: logstash
    user: root
    ports:
      - "5000:5000"
      - "9600:9600"
    volumes:
      - logstashdata01:/usr/share/logstash/data
      - "./logstash/pipelines/pipelines.yml:/etc/logstash/pipelines.yml:ro"
      - "./logstash/pipelines/filebeat_microservices_totem.conf:/usr/share/logstash/pipeline/conf.d/filebeat_microservices_totem.conf:ro"
      - "./logstash/pipelines/filebeat_totems_windows.conf:/usr/share/logstash/pipeline/conf.d/filebeat_totems_windows.conf:ro"
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=${ELASTIC_HOSTS}