volumes:
  logstashdata01:
    driver: local

networks:
  default:
    name: elastic
    external: false

services:
  logstash01:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    labels:
      co.elastic.logs/module: logstash
    user: root
    ports:
      - "${FILEBEAT_MICROSERVICES_PORT}:5000"
      - "${FILEBEAT_TOTEMS_WINDOWS_PORT}:5010"
      - "9600:9600"
    volumes:
      - logstashdata01:/usr/share/logstash/data
      - "./logstash/pipelines/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro"
      - "./logstash/pipelines/filebeat_totems_microservices.conf:/usr/share/logstash/pipeline/filebeat_totems_microservices.conf:ro"
      - "./logstash/pipelines/filebeat_totems_windows.conf:/usr/share/logstash/pipeline/filebeat_totems_windows.conf:ro"
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=${ELASTIC_HOSTS}
      - FILEBEAT_TOTEMS_MICROSERVICES_PORT=${FILEBEAT_TOTEMS_MICROSERVICES_PORT}
      - FILEBEAT_TOTEMS_WINDOWS_PORT=${FILEBEAT_TOTEMS_WINDOWS_PORT}